<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('Country')->truncate();

        DB::table('Country')->insert(
            array(
                array(
                    'CodeName2' => 'GB',
                    'CodeName3' => 'GBR',
                    'CountryID' => 1,
                    'Digital' => NULL,
                    'Name' => 'United Kingdom',
                    'Physical' => 15.0,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'US',
                    'CodeName3' => 'USA',
                    'CountryID' => 2,
                    'Digital' => NULL,
                    'Name' => 'United States',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'AF',
                    'CodeName3' => 'AFG',
                    'CountryID' => 3,
                    'Digital' => NULL,
                    'Name' => 'Afghanistan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AL',
                    'CodeName3' => 'ALB',
                    'CountryID' => 4,
                    'Digital' => NULL,
                    'Name' => 'Albania',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'DZ',
                    'CodeName3' => 'DZA',
                    'CountryID' => 5,
                    'Digital' => NULL,
                    'Name' => 'Algeria',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AS',
                    'CodeName3' => 'ASM',
                    'CountryID' => 6,
                    'Digital' => NULL,
                    'Name' => 'American Samoa',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AD',
                    'CodeName3' => 'AND',
                    'CountryID' => 7,
                    'Digital' => NULL,
                    'Name' => 'Andorra',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AO',
                    'CodeName3' => 'AGO',
                    'CountryID' => 8,
                    'Digital' => NULL,
                    'Name' => 'Angola',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AI',
                    'CodeName3' => 'AIA',
                    'CountryID' => 9,
                    'Digital' => NULL,
                    'Name' => 'Anguilla',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AQ',
                    'CodeName3' => 'ATA',
                    'CountryID' => 10,
                    'Digital' => NULL,
                    'Name' => 'Antarctica',
                    'Physical' => NULL,
                    'RegionID' => 4,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AG',
                    'CodeName3' => 'ATG',
                    'CountryID' => 11,
                    'Digital' => NULL,
                    'Name' => 'Antigua and Barbuda',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AR',
                    'CodeName3' => 'ARG',
                    'CountryID' => 12,
                    'Digital' => NULL,
                    'Name' => 'Argentina',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'AM',
                    'CodeName3' => 'ARM',
                    'CountryID' => 13,
                    'Digital' => NULL,
                    'Name' => 'Armenia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AW',
                    'CodeName3' => 'ABW',
                    'CountryID' => 14,
                    'Digital' => NULL,
                    'Name' => 'Aruba',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AU',
                    'CodeName3' => 'AUS',
                    'CountryID' => 15,
                    'Digital' => NULL,
                    'Name' => 'Australia',
                    'Physical' => NULL,
                    'RegionID' => 7,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'AT',
                    'CodeName3' => 'AUT',
                    'CountryID' => 16,
                    'Digital' => NULL,
                    'Name' => 'Austria',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AZ',
                    'CodeName3' => 'AZE',
                    'CountryID' => 17,
                    'Digital' => NULL,
                    'Name' => 'Azerbaijan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BS',
                    'CodeName3' => 'BHS',
                    'CountryID' => 18,
                    'Digital' => NULL,
                    'Name' => 'Bahamas',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BH',
                    'CodeName3' => 'BHR',
                    'CountryID' => 19,
                    'Digital' => NULL,
                    'Name' => 'Bahrain',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BD',
                    'CodeName3' => 'BGD',
                    'CountryID' => 20,
                    'Digital' => NULL,
                    'Name' => 'Bangladesh',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BB',
                    'CodeName3' => 'BRB',
                    'CountryID' => 21,
                    'Digital' => NULL,
                    'Name' => 'Barbados',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BY',
                    'CodeName3' => 'BLR',
                    'CountryID' => 22,
                    'Digital' => NULL,
                    'Name' => 'Belarus',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BE',
                    'CodeName3' => 'BEL',
                    'CountryID' => 23,
                    'Digital' => NULL,
                    'Name' => 'Belgium',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BZ',
                    'CodeName3' => 'BLZ',
                    'CountryID' => 24,
                    'Digital' => NULL,
                    'Name' => 'Belize',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BJ',
                    'CodeName3' => 'BEN',
                    'CountryID' => 25,
                    'Digital' => NULL,
                    'Name' => 'Benin',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BM',
                    'CodeName3' => 'BMU',
                    'CountryID' => 26,
                    'Digital' => NULL,
                    'Name' => 'Bermuda',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BT',
                    'CodeName3' => 'BTN',
                    'CountryID' => 27,
                    'Digital' => NULL,
                    'Name' => 'Bhutan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BO',
                    'CodeName3' => 'BOL',
                    'CountryID' => 28,
                    'Digital' => NULL,
                    'Name' => 'Bolivia',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BA',
                    'CodeName3' => 'BIH',
                    'CountryID' => 29,
                    'Digital' => NULL,
                    'Name' => 'Bosnia and Herzegowina',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BW',
                    'CodeName3' => 'BWA',
                    'CountryID' => 30,
                    'Digital' => NULL,
                    'Name' => 'Botswana',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BV',
                    'CodeName3' => 'BVT',
                    'CountryID' => 31,
                    'Digital' => NULL,
                    'Name' => 'Bouvet Island',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BR',
                    'CodeName3' => 'BRA',
                    'CountryID' => 32,
                    'Digital' => NULL,
                    'Name' => 'Brazil',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'IO',
                    'CodeName3' => 'IOT',
                    'CountryID' => 33,
                    'Digital' => NULL,
                    'Name' => 'British Indian Ocean Territory',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BN',
                    'CodeName3' => 'BRN',
                    'CountryID' => 34,
                    'Digital' => NULL,
                    'Name' => 'Brunei Darussalam',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BG',
                    'CodeName3' => 'BGR',
                    'CountryID' => 35,
                    'Digital' => NULL,
                    'Name' => 'Bulgaria',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BF',
                    'CodeName3' => 'BFA',
                    'CountryID' => 36,
                    'Digital' => NULL,
                    'Name' => 'Burkina Faso',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'BI',
                    'CodeName3' => 'BDI',
                    'CountryID' => 37,
                    'Digital' => NULL,
                    'Name' => 'Burundi',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KH',
                    'CodeName3' => 'KHM',
                    'CountryID' => 38,
                    'Digital' => NULL,
                    'Name' => 'Cambodia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CM',
                    'CodeName3' => 'CMR',
                    'CountryID' => 39,
                    'Digital' => NULL,
                    'Name' => 'Cameroon',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CA',
                    'CodeName3' => 'CAN',
                    'CountryID' => 40,
                    'Digital' => NULL,
                    'Name' => 'Canada',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'CV',
                    'CodeName3' => 'CPV',
                    'CountryID' => 41,
                    'Digital' => NULL,
                    'Name' => 'Cape Verde',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KY',
                    'CodeName3' => 'CYM',
                    'CountryID' => 42,
                    'Digital' => NULL,
                    'Name' => 'Cayman Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CF',
                    'CodeName3' => 'CAF',
                    'CountryID' => 43,
                    'Digital' => NULL,
                    'Name' => 'Central African Republic',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TD',
                    'CodeName3' => 'TCD',
                    'CountryID' => 44,
                    'Digital' => NULL,
                    'Name' => 'Chad',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CL',
                    'CodeName3' => 'CHL',
                    'CountryID' => 45,
                    'Digital' => NULL,
                    'Name' => 'Chile',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'CN',
                    'CodeName3' => 'CHN',
                    'CountryID' => 46,
                    'Digital' => NULL,
                    'Name' => 'China',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'CX',
                    'CodeName3' => 'CXR',
                    'CountryID' => 47,
                    'Digital' => NULL,
                    'Name' => 'Christmas Island',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CC',
                    'CodeName3' => 'CCK',
                    'CountryID' => 48,
                    'Digital' => NULL,
                    'Name' => 'Cocos (Keeling) Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CO',
                    'CodeName3' => 'COL',
                    'CountryID' => 49,
                    'Digital' => NULL,
                    'Name' => 'Colombia',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KM',
                    'CodeName3' => 'COM',
                    'CountryID' => 50,
                    'Digital' => NULL,
                    'Name' => 'Comoros',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CD',
                    'CodeName3' => 'COD',
                    'CountryID' => 51,
                    'Digital' => NULL,
                    'Name' => 'Congo',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CK',
                    'CodeName3' => 'COK',
                    'CountryID' => 52,
                    'Digital' => NULL,
                    'Name' => 'Cook Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CR',
                    'CodeName3' => 'CRI',
                    'CountryID' => 53,
                    'Digital' => NULL,
                    'Name' => 'Costa Rica',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CI',
                    'CodeName3' => 'CIV',
                    'CountryID' => 54,
                    'Digital' => NULL,
                    'Name' => 'Cote D\'Ivoire',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'HR',
                    'CodeName3' => 'HRV',
                    'CountryID' => 55,
                    'Digital' => NULL,
                    'Name' => 'Croatia (local name: Hrvatska)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CU',
                    'CodeName3' => 'CUB',
                    'CountryID' => 56,
                    'Digital' => NULL,
                    'Name' => 'Cuba',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CY',
                    'CodeName3' => 'CYP',
                    'CountryID' => 57,
                    'Digital' => NULL,
                    'Name' => 'Cyprus',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CZ',
                    'CodeName3' => 'CZE',
                    'CountryID' => 58,
                    'Digital' => NULL,
                    'Name' => 'Czech Republic',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'DK',
                    'CodeName3' => 'DNK',
                    'CountryID' => 59,
                    'Digital' => NULL,
                    'Name' => 'Denmark',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'DJ',
                    'CodeName3' => 'DJI',
                    'CountryID' => 60,
                    'Digital' => NULL,
                    'Name' => 'Djibouti',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'DM',
                    'CodeName3' => 'DMA',
                    'CountryID' => 61,
                    'Digital' => NULL,
                    'Name' => 'Dominica',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'DO',
                    'CodeName3' => 'DOM',
                    'CountryID' => 62,
                    'Digital' => NULL,
                    'Name' => 'Dominican Republic',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => '',
                    'CodeName3' => '',
                    'CountryID' => 63,
                    'Digital' => NULL,
                    'Name' => 'East Timor',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'EC',
                    'CodeName3' => 'ECU',
                    'CountryID' => 64,
                    'Digital' => NULL,
                    'Name' => 'Ecuador',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'EG',
                    'CodeName3' => 'EGY',
                    'CountryID' => 65,
                    'Digital' => NULL,
                    'Name' => 'Egypt',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SV',
                    'CodeName3' => 'SLV',
                    'CountryID' => 66,
                    'Digital' => NULL,
                    'Name' => 'El Salvador',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GQ',
                    'CodeName3' => 'GNQ',
                    'CountryID' => 67,
                    'Digital' => NULL,
                    'Name' => 'Equatorial Guinea',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ER',
                    'CodeName3' => 'ERI',
                    'CountryID' => 68,
                    'Digital' => NULL,
                    'Name' => 'Eritrea',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'EE',
                    'CodeName3' => 'EST',
                    'CountryID' => 69,
                    'Digital' => NULL,
                    'Name' => 'Estonia',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ET',
                    'CodeName3' => 'ETH',
                    'CountryID' => 70,
                    'Digital' => NULL,
                    'Name' => 'Ethiopia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'FO',
                    'CodeName3' => 'FOR',
                    'CountryID' => 71,
                    'Digital' => NULL,
                    'Name' => 'Faeroe Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'FK',
                    'CodeName3' => 'FLK',
                    'CountryID' => 72,
                    'Digital' => NULL,
                    'Name' => 'Falkland Islands (Malvinas)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'FJ',
                    'CodeName3' => 'FJI',
                    'CountryID' => 73,
                    'Digital' => NULL,
                    'Name' => 'Fiji',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'FI',
                    'CodeName3' => 'FIN',
                    'CountryID' => 74,
                    'Digital' => NULL,
                    'Name' => 'Finland',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'FR',
                    'CodeName3' => 'FRA',
                    'CountryID' => 75,
                    'Digital' => NULL,
                    'Name' => 'France',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => '',
                    'CodeName3' => '',
                    'CountryID' => 76,
                    'Digital' => NULL,
                    'Name' => 'France, Metropolitan',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GF',
                    'CodeName3' => 'GUF',
                    'CountryID' => 77,
                    'Digital' => NULL,
                    'Name' => 'French Guiana',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PF',
                    'CodeName3' => 'PYF',
                    'CountryID' => 78,
                    'Digital' => NULL,
                    'Name' => 'French Polynesia',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TF',
                    'CodeName3' => 'ATF',
                    'CountryID' => 79,
                    'Digital' => NULL,
                    'Name' => 'French Southern Territories',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GA',
                    'CodeName3' => 'GAB',
                    'CountryID' => 80,
                    'Digital' => NULL,
                    'Name' => 'Gabon',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GM',
                    'CodeName3' => 'GMB',
                    'CountryID' => 81,
                    'Digital' => NULL,
                    'Name' => 'Gambia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GE',
                    'CodeName3' => 'GEO',
                    'CountryID' => 82,
                    'Digital' => NULL,
                    'Name' => 'Georgia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'DE',
                    'CodeName3' => 'DEU',
                    'CountryID' => 83,
                    'Digital' => NULL,
                    'Name' => 'Germany',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'GH',
                    'CodeName3' => 'GHA',
                    'CountryID' => 84,
                    'Digital' => NULL,
                    'Name' => 'Ghana',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GI',
                    'CodeName3' => 'GIB',
                    'CountryID' => 85,
                    'Digital' => NULL,
                    'Name' => 'Gibraltar',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GR',
                    'CodeName3' => 'GRC',
                    'CountryID' => 86,
                    'Digital' => NULL,
                    'Name' => 'Greece',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GL',
                    'CodeName3' => 'GRL',
                    'CountryID' => 87,
                    'Digital' => NULL,
                    'Name' => 'Greenland',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GD',
                    'CodeName3' => 'GRD',
                    'CountryID' => 88,
                    'Digital' => NULL,
                    'Name' => 'Grenada',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GP',
                    'CodeName3' => 'GLP',
                    'CountryID' => 89,
                    'Digital' => NULL,
                    'Name' => 'Guadeloupe',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GU',
                    'CodeName3' => 'GUM',
                    'CountryID' => 90,
                    'Digital' => NULL,
                    'Name' => 'Guam',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GT',
                    'CodeName3' => 'GTM',
                    'CountryID' => 91,
                    'Digital' => NULL,
                    'Name' => 'Guatemala',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GN',
                    'CodeName3' => 'GIN',
                    'CountryID' => 92,
                    'Digital' => NULL,
                    'Name' => 'Guinea',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GW',
                    'CodeName3' => 'GNB',
                    'CountryID' => 93,
                    'Digital' => NULL,
                    'Name' => 'Guinea-Bissau',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'GY',
                    'CodeName3' => 'GUY',
                    'CountryID' => 94,
                    'Digital' => NULL,
                    'Name' => 'Guyana',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'HT',
                    'CodeName3' => 'HTI',
                    'CountryID' => 95,
                    'Digital' => NULL,
                    'Name' => 'Haiti',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'HM',
                    'CodeName3' => 'HMD',
                    'CountryID' => 96,
                    'Digital' => NULL,
                    'Name' => 'Heard and McDonald Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'HN',
                    'CodeName3' => 'HND',
                    'CountryID' => 97,
                    'Digital' => NULL,
                    'Name' => 'Honduras',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'HK',
                    'CodeName3' => 'HKG',
                    'CountryID' => 98,
                    'Digital' => NULL,
                    'Name' => 'Hong Kong',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'HU',
                    'CodeName3' => 'HUN',
                    'CountryID' => 99,
                    'Digital' => NULL,
                    'Name' => 'Hungary',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'IS',
                    'CodeName3' => 'ISL',
                    'CountryID' => 100,
                    'Digital' => NULL,
                    'Name' => 'Iceland',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'IN',
                    'CodeName3' => 'IND',
                    'CountryID' => 101,
                    'Digital' => NULL,
                    'Name' => 'India',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'ID',
                    'CodeName3' => 'IDN',
                    'CountryID' => 102,
                    'Digital' => NULL,
                    'Name' => 'Indonesia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'IR',
                    'CodeName3' => 'IRN',
                    'CountryID' => 103,
                    'Digital' => NULL,
                    'Name' => 'Iran (Islamic Republic of)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'IQ',
                    'CodeName3' => 'IRQ',
                    'CountryID' => 104,
                    'Digital' => NULL,
                    'Name' => 'Iraq',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'IE',
                    'CodeName3' => 'IRL',
                    'CountryID' => 105,
                    'Digital' => NULL,
                    'Name' => 'Ireland',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'IL',
                    'CodeName3' => 'ISR',
                    'CountryID' => 106,
                    'Digital' => NULL,
                    'Name' => 'Israel',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'IT',
                    'CodeName3' => 'ITA',
                    'CountryID' => 107,
                    'Digital' => NULL,
                    'Name' => 'Italy',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'JM',
                    'CodeName3' => 'JAM',
                    'CountryID' => 108,
                    'Digital' => NULL,
                    'Name' => 'Jamaica',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'JP',
                    'CodeName3' => 'JPN',
                    'CountryID' => 109,
                    'Digital' => NULL,
                    'Name' => 'Japan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'JO',
                    'CodeName3' => 'JOR',
                    'CountryID' => 110,
                    'Digital' => NULL,
                    'Name' => 'Jordan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KZ',
                    'CodeName3' => 'KAZ',
                    'CountryID' => 111,
                    'Digital' => NULL,
                    'Name' => 'Kazakhstan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KE',
                    'CodeName3' => 'KEN',
                    'CountryID' => 112,
                    'Digital' => NULL,
                    'Name' => 'Kenya',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KI',
                    'CodeName3' => 'KIR',
                    'CountryID' => 113,
                    'Digital' => NULL,
                    'Name' => 'Kiribati',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KP',
                    'CodeName3' => 'PRK',
                    'CountryID' => 114,
                    'Digital' => NULL,
                    'Name' => 'South Korea',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'KR',
                    'CodeName3' => 'KOR',
                    'CountryID' => 115,
                    'Digital' => NULL,
                    'Name' => 'Korea, Republic of',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KW',
                    'CodeName3' => 'KWT',
                    'CountryID' => 116,
                    'Digital' => NULL,
                    'Name' => 'Kuwait',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KG',
                    'CodeName3' => 'KGZ',
                    'CountryID' => 117,
                    'Digital' => NULL,
                    'Name' => 'Kyrgyzstan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LA',
                    'CodeName3' => 'LAO',
                    'CountryID' => 118,
                    'Digital' => NULL,
                    'Name' => 'Lao People\'s Democratic Republic',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LV',
                    'CodeName3' => 'LVA',
                    'CountryID' => 119,
                    'Digital' => NULL,
                    'Name' => 'Latvia',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LB',
                    'CodeName3' => 'LBN',
                    'CountryID' => 120,
                    'Digital' => NULL,
                    'Name' => 'Lebanon',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LS',
                    'CodeName3' => 'LSO',
                    'CountryID' => 121,
                    'Digital' => NULL,
                    'Name' => 'Lesotho',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LR',
                    'CodeName3' => 'LBR',
                    'CountryID' => 122,
                    'Digital' => NULL,
                    'Name' => 'Liberia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LY',
                    'CodeName3' => 'LBY',
                    'CountryID' => 123,
                    'Digital' => NULL,
                    'Name' => 'Libyan Arab Jamahiriya',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LI',
                    'CodeName3' => 'LIE',
                    'CountryID' => 124,
                    'Digital' => NULL,
                    'Name' => 'Liechtenstein',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LT',
                    'CodeName3' => 'LTU',
                    'CountryID' => 125,
                    'Digital' => NULL,
                    'Name' => 'Lithuania',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LU',
                    'CodeName3' => 'LUX',
                    'CountryID' => 126,
                    'Digital' => NULL,
                    'Name' => 'Luxembourg',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MO',
                    'CodeName3' => 'MAC',
                    'CountryID' => 127,
                    'Digital' => NULL,
                    'Name' => 'Macau',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MK',
                    'CodeName3' => 'MKD',
                    'CountryID' => 128,
                    'Digital' => NULL,
                    'Name' => 'Macedonia, the former Yugoslav Republic of',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MG',
                    'CodeName3' => 'MDG',
                    'CountryID' => 129,
                    'Digital' => NULL,
                    'Name' => 'Madagascar',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MW',
                    'CodeName3' => 'MWI',
                    'CountryID' => 130,
                    'Digital' => NULL,
                    'Name' => 'Malawi',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MY',
                    'CodeName3' => 'MYS',
                    'CountryID' => 131,
                    'Digital' => NULL,
                    'Name' => 'Malaysia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'MV',
                    'CodeName3' => 'MDV',
                    'CountryID' => 132,
                    'Digital' => NULL,
                    'Name' => 'Maldives',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ML',
                    'CodeName3' => 'MLI',
                    'CountryID' => 133,
                    'Digital' => NULL,
                    'Name' => 'Mali',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MT',
                    'CodeName3' => 'MLT',
                    'CountryID' => 134,
                    'Digital' => NULL,
                    'Name' => 'Malta',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MH',
                    'CodeName3' => 'MHL',
                    'CountryID' => 135,
                    'Digital' => NULL,
                    'Name' => 'Marshall Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MQ',
                    'CodeName3' => 'MTQ',
                    'CountryID' => 136,
                    'Digital' => NULL,
                    'Name' => 'Martinique',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MR',
                    'CodeName3' => 'MRT',
                    'CountryID' => 137,
                    'Digital' => NULL,
                    'Name' => 'Mauritania',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MU',
                    'CodeName3' => 'MUS',
                    'CountryID' => 138,
                    'Digital' => NULL,
                    'Name' => 'Mauritius',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'YT',
                    'CodeName3' => 'MYT',
                    'CountryID' => 139,
                    'Digital' => NULL,
                    'Name' => 'Mayotte',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MX',
                    'CodeName3' => 'MEX',
                    'CountryID' => 140,
                    'Digital' => NULL,
                    'Name' => 'Mexico',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'FM',
                    'CodeName3' => 'FSM',
                    'CountryID' => 141,
                    'Digital' => NULL,
                    'Name' => 'Micronesia, Federated States of',
                    'Physical' => NULL,
                    'RegionID' => 7,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MD',
                    'CodeName3' => 'MDA',
                    'CountryID' => 142,
                    'Digital' => NULL,
                    'Name' => 'Moldova, Republic of',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MC',
                    'CodeName3' => 'MCO',
                    'CountryID' => 143,
                    'Digital' => NULL,
                    'Name' => 'Monaco',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MG',
                    'CodeName3' => 'MNG',
                    'CountryID' => 144,
                    'Digital' => NULL,
                    'Name' => 'Mongolia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MS',
                    'CodeName3' => 'MSR',
                    'CountryID' => 145,
                    'Digital' => NULL,
                    'Name' => 'Montserrat',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MA',
                    'CodeName3' => 'MAR',
                    'CountryID' => 146,
                    'Digital' => NULL,
                    'Name' => 'Morocco',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MZ',
                    'CodeName3' => 'MOZ',
                    'CountryID' => 147,
                    'Digital' => NULL,
                    'Name' => 'Mozambique',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MM',
                    'CodeName3' => 'MMR',
                    'CountryID' => 148,
                    'Digital' => NULL,
                    'Name' => 'Myanmar',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NA',
                    'CodeName3' => 'NAM',
                    'CountryID' => 149,
                    'Digital' => NULL,
                    'Name' => 'Namibia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NR',
                    'CodeName3' => 'NRU',
                    'CountryID' => 150,
                    'Digital' => NULL,
                    'Name' => 'Nauru',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NP',
                    'CodeName3' => 'NPL',
                    'CountryID' => 151,
                    'Digital' => NULL,
                    'Name' => 'Nepal',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NL',
                    'CodeName3' => 'NLD',
                    'CountryID' => 152,
                    'Digital' => NULL,
                    'Name' => 'Netherlands',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AN',
                    'CodeName3' => 'ANT',
                    'CountryID' => 153,
                    'Digital' => NULL,
                    'Name' => 'Netherlands Antilles',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NC',
                    'CodeName3' => 'NCL',
                    'CountryID' => 154,
                    'Digital' => NULL,
                    'Name' => 'New Caledonia',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NZ',
                    'CodeName3' => 'NZL',
                    'CountryID' => 155,
                    'Digital' => NULL,
                    'Name' => 'New Zealand',
                    'Physical' => NULL,
                    'RegionID' => 7,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'NI',
                    'CodeName3' => 'NIC',
                    'CountryID' => 156,
                    'Digital' => NULL,
                    'Name' => 'Nicaragua',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NE',
                    'CodeName3' => 'NER',
                    'CountryID' => 157,
                    'Digital' => NULL,
                    'Name' => 'Niger',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NG',
                    'CodeName3' => 'NGA',
                    'CountryID' => 158,
                    'Digital' => NULL,
                    'Name' => 'Nigeria',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NU',
                    'CodeName3' => 'NIU',
                    'CountryID' => 159,
                    'Digital' => NULL,
                    'Name' => 'Niue',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NF',
                    'CodeName3' => 'NFK',
                    'CountryID' => 160,
                    'Digital' => NULL,
                    'Name' => 'Norfolk Island',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MP',
                    'CodeName3' => 'MNP',
                    'CountryID' => 161,
                    'Digital' => NULL,
                    'Name' => 'Northern Mariana Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'NO',
                    'CodeName3' => 'NOR',
                    'CountryID' => 162,
                    'Digital' => NULL,
                    'Name' => 'Norway',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'OM',
                    'CodeName3' => 'OMN',
                    'CountryID' => 163,
                    'Digital' => NULL,
                    'Name' => 'Oman',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PK',
                    'CodeName3' => 'PAK',
                    'CountryID' => 164,
                    'Digital' => NULL,
                    'Name' => 'Pakistan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'PW',
                    'CodeName3' => 'PLW',
                    'CountryID' => 165,
                    'Digital' => NULL,
                    'Name' => 'Palau',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PA',
                    'CodeName3' => 'PAN',
                    'CountryID' => 166,
                    'Digital' => NULL,
                    'Name' => 'Panama',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PG',
                    'CodeName3' => 'PNG',
                    'CountryID' => 167,
                    'Digital' => NULL,
                    'Name' => 'Papua New Guinea',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PY',
                    'CodeName3' => 'PRY',
                    'CountryID' => 168,
                    'Digital' => NULL,
                    'Name' => 'Paraguay',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PE',
                    'CodeName3' => 'PER',
                    'CountryID' => 169,
                    'Digital' => NULL,
                    'Name' => 'Peru',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'PH',
                    'CodeName3' => 'PHL',
                    'CountryID' => 170,
                    'Digital' => NULL,
                    'Name' => 'Philippines',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'PN',
                    'CodeName3' => 'PCN',
                    'CountryID' => 171,
                    'Digital' => NULL,
                    'Name' => 'Pitcairn',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PL',
                    'CodeName3' => 'POL',
                    'CountryID' => 172,
                    'Digital' => NULL,
                    'Name' => 'Poland',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'PT',
                    'CodeName3' => 'PRT',
                    'CountryID' => 173,
                    'Digital' => NULL,
                    'Name' => 'Portugal',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PR',
                    'CodeName3' => 'PRI',
                    'CountryID' => 174,
                    'Digital' => NULL,
                    'Name' => 'Puerto Rico',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'QA',
                    'CodeName3' => 'QAT',
                    'CountryID' => 175,
                    'Digital' => NULL,
                    'Name' => 'Qatar',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'RE',
                    'CodeName3' => 'REU',
                    'CountryID' => 176,
                    'Digital' => NULL,
                    'Name' => 'Reunion',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'RO',
                    'CodeName3' => 'ROU',
                    'CountryID' => 177,
                    'Digital' => NULL,
                    'Name' => 'Romania',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'RU',
                    'CodeName3' => 'RUS',
                    'CountryID' => 178,
                    'Digital' => NULL,
                    'Name' => 'Russia',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'RW',
                    'CodeName3' => 'RWA',
                    'CountryID' => 179,
                    'Digital' => NULL,
                    'Name' => 'Rwanda',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'KN',
                    'CodeName3' => 'KNA',
                    'CountryID' => 180,
                    'Digital' => NULL,
                    'Name' => 'Saint Kitts and Nevis',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LC',
                    'CodeName3' => 'LCA',
                    'CountryID' => 181,
                    'Digital' => NULL,
                    'Name' => 'Saint Lucia',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VC',
                    'CodeName3' => 'VCT',
                    'CountryID' => 182,
                    'Digital' => NULL,
                    'Name' => 'Saint Vincent and the Grenadines',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'WS',
                    'CodeName3' => 'WSM',
                    'CountryID' => 183,
                    'Digital' => NULL,
                    'Name' => 'Samoa',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SM',
                    'CodeName3' => 'SMR',
                    'CountryID' => 184,
                    'Digital' => NULL,
                    'Name' => 'San Marino',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ST',
                    'CodeName3' => 'STP',
                    'CountryID' => 185,
                    'Digital' => NULL,
                    'Name' => 'Sao Tome and Principe',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SA',
                    'CodeName3' => 'SAU',
                    'CountryID' => 186,
                    'Digital' => NULL,
                    'Name' => 'Saudi Arabia',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SN',
                    'CodeName3' => 'SEN',
                    'CountryID' => 187,
                    'Digital' => NULL,
                    'Name' => 'Senegal',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SC',
                    'CodeName3' => 'SYC',
                    'CountryID' => 188,
                    'Digital' => NULL,
                    'Name' => 'Seychelles',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SL',
                    'CodeName3' => 'SLE',
                    'CountryID' => 189,
                    'Digital' => NULL,
                    'Name' => 'Sierra Leone',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SG',
                    'CodeName3' => 'SGP',
                    'CountryID' => 190,
                    'Digital' => NULL,
                    'Name' => 'Singapore',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'SK',
                    'CodeName3' => 'SVK',
                    'CountryID' => 191,
                    'Digital' => NULL,
                    'Name' => 'Slovakia (Slovak Republic)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SI',
                    'CodeName3' => 'SVN',
                    'CountryID' => 192,
                    'Digital' => NULL,
                    'Name' => 'Slovenia',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SB',
                    'CodeName3' => 'SLB',
                    'CountryID' => 193,
                    'Digital' => NULL,
                    'Name' => 'Solomon Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SO',
                    'CodeName3' => 'SOM',
                    'CountryID' => 194,
                    'Digital' => NULL,
                    'Name' => 'Somalia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ZA',
                    'CodeName3' => 'ZAF',
                    'CountryID' => 195,
                    'Digital' => NULL,
                    'Name' => 'South Africa',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'ES',
                    'CodeName3' => 'ESP',
                    'CountryID' => 196,
                    'Digital' => NULL,
                    'Name' => 'Spain',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'LK',
                    'CodeName3' => 'LKA',
                    'CountryID' => 197,
                    'Digital' => NULL,
                    'Name' => 'Sri Lanka',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'SH',
                    'CodeName3' => 'SHN',
                    'CountryID' => 198,
                    'Digital' => NULL,
                    'Name' => 'St. Helena',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'PM',
                    'CodeName3' => 'SPM',
                    'CountryID' => 199,
                    'Digital' => NULL,
                    'Name' => 'St. Pierre and Miquelon',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SN',
                    'CodeName3' => 'SDN',
                    'CountryID' => 200,
                    'Digital' => NULL,
                    'Name' => 'Sudan',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SR',
                    'CodeName3' => 'SUR',
                    'CountryID' => 201,
                    'Digital' => NULL,
                    'Name' => 'Suriname',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SJ',
                    'CodeName3' => 'SJM',
                    'CountryID' => 202,
                    'Digital' => NULL,
                    'Name' => 'Svalbard and Jan Mayen Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SZ',
                    'CodeName3' => 'SWZ',
                    'CountryID' => 203,
                    'Digital' => NULL,
                    'Name' => 'Swaziland',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'SE',
                    'CodeName3' => 'SWE',
                    'CountryID' => 204,
                    'Digital' => NULL,
                    'Name' => 'Sweden',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'CH',
                    'CodeName3' => 'CHE',
                    'CountryID' => 205,
                    'Digital' => NULL,
                    'Name' => 'Switzerland',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'SY',
                    'CodeName3' => 'SYR',
                    'CountryID' => 206,
                    'Digital' => NULL,
                    'Name' => 'Syrian Arab Republic',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TW',
                    'CodeName3' => 'TWN',
                    'CountryID' => 207,
                    'Digital' => NULL,
                    'Name' => 'Taiwan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'TJ',
                    'CodeName3' => 'TJK',
                    'CountryID' => 208,
                    'Digital' => NULL,
                    'Name' => 'Tajikistan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TZ',
                    'CodeName3' => 'TZA',
                    'CountryID' => 209,
                    'Digital' => NULL,
                    'Name' => 'Tanzania, United Republic of',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TH',
                    'CodeName3' => 'THA',
                    'CountryID' => 210,
                    'Digital' => NULL,
                    'Name' => 'Thailand',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'TG',
                    'CodeName3' => 'TGO',
                    'CountryID' => 211,
                    'Digital' => NULL,
                    'Name' => 'Togo',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TK',
                    'CodeName3' => 'TKL',
                    'CountryID' => 212,
                    'Digital' => NULL,
                    'Name' => 'Tokelau',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TO',
                    'CodeName3' => 'TON',
                    'CountryID' => 213,
                    'Digital' => NULL,
                    'Name' => 'Tonga',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TT',
                    'CodeName3' => 'TTO',
                    'CountryID' => 214,
                    'Digital' => NULL,
                    'Name' => 'Trinidad and Tobago',
                    'Physical' => NULL,
                    'RegionID' => 2,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TN',
                    'CodeName3' => 'TUN',
                    'CountryID' => 215,
                    'Digital' => NULL,
                    'Name' => 'Tunisia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TR',
                    'CodeName3' => 'TUR',
                    'CountryID' => 216,
                    'Digital' => NULL,
                    'Name' => 'Turkey',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TM',
                    'CodeName3' => 'TKM',
                    'CountryID' => 217,
                    'Digital' => NULL,
                    'Name' => 'Turkmenistan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TC',
                    'CodeName3' => 'TCA',
                    'CountryID' => 218,
                    'Digital' => NULL,
                    'Name' => 'Turks and Caicos Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'TV',
                    'CodeName3' => 'TUV',
                    'CountryID' => 219,
                    'Digital' => NULL,
                    'Name' => 'Tuvalu',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'UG',
                    'CodeName3' => 'UGA',
                    'CountryID' => 220,
                    'Digital' => NULL,
                    'Name' => 'Uganda',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'UA',
                    'CodeName3' => 'UKR',
                    'CountryID' => 221,
                    'Digital' => NULL,
                    'Name' => 'Ukraine',
                    'Physical' => NULL,
                    'RegionID' => 6,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'AE',
                    'CodeName3' => 'ARE',
                    'CountryID' => 222,
                    'Digital' => NULL,
                    'Name' => 'United Arab Emirates',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'UM',
                    'CodeName3' => 'UMI',
                    'CountryID' => 225,
                    'Digital' => NULL,
                    'Name' => 'United States Minor Outlying Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'UY',
                    'CodeName3' => 'URY',
                    'CountryID' => 226,
                    'Digital' => NULL,
                    'Name' => 'Uruguay',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'UZ',
                    'CodeName3' => 'UZB',
                    'CountryID' => 227,
                    'Digital' => NULL,
                    'Name' => 'Uzbekistan',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VU',
                    'CodeName3' => 'VUT',
                    'CountryID' => 228,
                    'Digital' => NULL,
                    'Name' => 'Vanuatu',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VA',
                    'CodeName3' => 'VAT',
                    'CountryID' => 229,
                    'Digital' => NULL,
                    'Name' => 'Vatican City State (Holy See)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VE',
                    'CodeName3' => 'VEN',
                    'CountryID' => 230,
                    'Digital' => NULL,
                    'Name' => 'Venezuela',
                    'Physical' => NULL,
                    'RegionID' => 3,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VN',
                    'CodeName3' => 'VNM',
                    'CountryID' => 231,
                    'Digital' => NULL,
                    'Name' => 'Vietnam',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VG',
                    'CodeName3' => 'VGB',
                    'CountryID' => 232,
                    'Digital' => NULL,
                    'Name' => 'Virgin Islands (British)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'VI',
                    'CodeName3' => 'VIR',
                    'CountryID' => 233,
                    'Digital' => NULL,
                    'Name' => 'Virgin Islands (U.S.)',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'WF',
                    'CodeName3' => 'WLF',
                    'CountryID' => 234,
                    'Digital' => NULL,
                    'Name' => 'Wallis And Futuna Islands',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'EH',
                    'CodeName3' => 'ESH',
                    'CountryID' => 235,
                    'Digital' => NULL,
                    'Name' => 'Western Sahara',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'YE',
                    'CodeName3' => 'YEM',
                    'CountryID' => 236,
                    'Digital' => NULL,
                    'Name' => 'Yemen',
                    'Physical' => NULL,
                    'RegionID' => 5,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'YU',
                    'CodeName3' => 'YUG',
                    'CountryID' => 237,
                    'Digital' => NULL,
                    'Name' => 'Yugoslavia',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ZR',
                    'CodeName3' => 'ZAR',
                    'CountryID' => 238,
                    'Digital' => NULL,
                    'Name' => 'Zaire',
                    'Physical' => NULL,
                    'RegionID' => NULL,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ZM',
                    'CodeName3' => 'ZMB',
                    'CountryID' => 239,
                    'Digital' => NULL,
                    'Name' => 'Zambia',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'ZW',
                    'CodeName3' => 'ZWE',
                    'CountryID' => 240,
                    'Digital' => NULL,
                    'Name' => 'Zimbabwe',
                    'Physical' => NULL,
                    'RegionID' => 1,
                    'Status' => 0,
                ),

                array(
                    'CodeName2' => 'MD',
                    'CodeName3' => 'MDA',
                    'CountryID' => 241,
                    'Digital' => 0.0,
                    'Name' => 'Moldova',
                    'Physical' => 0.0,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'NI',
                    'CodeName3' => 'NIR',
                    'CountryID' => 242,
                    'Digital' => 0.0,
                    'Name' => 'Northern Ireland',
                    'Physical' => 0.0,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'IC',
                    'CodeName3' => 'ICS',
                    'CountryID' => 243,
                    'Digital' => 0.0,
                    'Name' => 'Canary Islands',
                    'Physical' => 0.0,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'JE',
                    'CodeName3' => 'JER',
                    'CountryID' => 244,
                    'Digital' => 0.0,
                    'Name' => 'Jersey',
                    'Physical' => 0.0,
                    'RegionID' => 6,
                    'Status' => 1,
                ),

                array(
                    'CodeName2' => 'GG',
                    'CodeName3' => 'GGY',
                    'CountryID' => 245,
                    'Digital' => 0.0,
                    'Name' => 'Guernsey',
                    'Physical' => 0.0,
                    'RegionID' => 6,
                    'Status' => 1,
                ),
            )
        );


    }
}