<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('doctor')->delete();

        DB::table('doctor')->insert(
            array(

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Holidays Accomadation',
                    'Address2' => 'Flat 7',
                    'Address3' => '8 Cheniston Gardens',
                    'Address4' => 'London',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789203,
                    'DoctorID' => 10,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '70336704',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789203,
                    'Name' => 'Dr Stamatios',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'W8 6TQ',
                    'Status' => 2,
                    'Surname' => 'Poupalos',
                    'Telephone' => '',
                    'Title' => '',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '90 Impasse des Tilleuls',
                    'Address2' => 'Amphion les Bains',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 75,
                    'CreatedDate' => 1569789369,
                    'DoctorID' => 11,
                    'DoctorType' => 2,
                    'Email' => '',
                    'GMCNO' => '89020313001',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789369,
                    'Name' => 'Abraham',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => '74500 ',
                    'Status' => 2,
                    'Surname' => 'Brons',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '65 Bradford Street',
                    'Address2' => 'Bolton',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1581864450,
                    'DoctorID' => 12,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '4149602',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1581864450,
                    'Name' => 'Abubakr',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL2 1HT',
                    'Status' => 2,
                    'Surname' => 'Zarrouk',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Franz-Marc-Str. 6',
                    'Address2' => 'Geilenkirchen',
                    'Address3' => NULL,
                    'Address4' => NULL,
                    'CompanyName' => NULL,
                    'CountryID' => 83,
                    'CreatedDate' => 1562152383,
                    'DoctorID' => 13,
                    'DoctorType' => 2,
                    'Email' => NULL,
                    'GMCNO' => '135056',
                    'MedicalInsuranceNo' => NULL,
                    'Mobile' => NULL,
                    'ModifiedDate' => 1562152383,
                    'Name' => 'Maria',
                    'Notes' => NULL,
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'D-52511',
                    'Status' => 0,
                    'Surname' => 'Collison',
                    'Telephone' => NULL,
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str. Tudor Vladimirescu Nr 1',
                    'Address2' => 'Chisineu Cris',
                    'Address3' => 'Arad',
                    'Address4' => NULL,
                    'CompanyName' => NULL,
                    'CountryID' => 177,
                    'CreatedDate' => 1531480961,
                    'DoctorID' => 14,
                    'DoctorType' => 2,
                    'Email' => NULL,
                    'GMCNO' => '1013',
                    'MedicalInsuranceNo' => NULL,
                    'Mobile' => NULL,
                    'ModifiedDate' => 1531480961,
                    'Name' => 'Adnan',
                    'Notes' => NULL,
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => '315100',
                    'Status' => 0,
                    'Surname' => 'El-Kharoubi',
                    'Telephone' => NULL,
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Erwin-Von-Witzleben-Str 17',
                    'Address2' => '40474',
                    'Address3' => 'Dusseldorf',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 83,
                    'CreatedDate' => 1570035852,
                    'DoctorID' => 15,
                    'DoctorType' => 2,
                    'Email' => '',
                    'GMCNO' => '095658',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1570035852,
                    'Name' => 'Helmut',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => '',
                    'Status' => 2,
                    'Surname' => 'Benkert',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '35 norden way',
                    'Address2' => 'Norden',
                    'Address3' => 'Rochdale',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789257,
                    'DoctorID' => 16,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '4594570',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789257,
                    'Name' => 'Dr Maqbool',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'OL11 5TD',
                    'Status' => 2,
                    'Surname' => 'Ahmad',
                    'Telephone' => '',
                    'Title' => '',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '17 long mead ave',
                    'Address2' => 'Hazelhurst',
                    'Address3' => 'Stockport',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789397,
                    'DoctorID' => 17,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '1469956',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789397,
                    'Name' => 'Dr Christopher',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'SK7 5PG',
                    'Status' => 2,
                    'Surname' => 'Martin',
                    'Telephone' => '',
                    'Title' => '',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '5 The Walkway',
                    'Address2' => 'Bolton',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789280,
                    'DoctorID' => 18,
                    'DoctorType' => 1,
                    'Email' => 'snaseef@hotmail.com',
                    'GMCNO' => '5201569',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07817559419',
                    'ModifiedDate' => 1569789280,
                    'Name' => 'Samir ',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL3 4NT',
                    'Status' => 2,
                    'Surname' => 'Naseef',
                    'Telephone' => '07817559419',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Flat 13',
                    'Address2' => 'Knowles Court',
                    'Address3' => 'Eccles Old Road',
                    'Address4' => 'Salford',
                    'CompanyName' => 'BIMS',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789417,
                    'DoctorID' => 20,
                    'DoctorType' => 1,
                    'Email' => 'drshivakumarlh@gmail.com',
                    'GMCNO' => '7020910',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07951192615',
                    'ModifiedDate' => 1569789417,
                    'Name' => 'Shivakumar',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'M6 8ES',
                    'Status' => 2,
                    'Surname' => 'Honnakatti',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Foxes Green Farm',
                    'Address2' => 'Foxwist Green',
                    'Address3' => 'Whitegate',
                    'Address4' => 'Cheshire',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789337,
                    'DoctorID' => 21,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '3056712',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789337,
                    'Name' => 'Paul',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'CW8 2BJ',
                    'Status' => 2,
                    'Surname' => 'Cronin',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '66 Grove Park',
                    'Address2' => 'Mottingham',
                    'Address3' => 'London',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789500,
                    'DoctorID' => 22,
                    'DoctorType' => 1,
                    'Email' => 'jaypatel316@hotmail.com',
                    'GMCNO' => '6128026',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07950136776',
                    'ModifiedDate' => 1569789500,
                    'Name' => 'Jaykumar J',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => ' SE9 4QB',
                    'Status' => 2,
                    'Surname' => 'Patel',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '17 Gardeners Mews',
                    'Address2' => 'Blackpool',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => 'Gerry Diamond',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789529,
                    'DoctorID' => 23,
                    'DoctorType' => 3,
                    'Email' => 'g.diamond1@btinternet.com',
                    'GMCNO' => '2030776',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07795 515 800',
                    'ModifiedDate' => 1569789529,
                    'Name' => 'Gerry',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'FY1 2EH',
                    'Status' => 2,
                    'Surname' => 'Diamond',
                    'Telephone' => '07795 515 800',
                    'Title' => 'Mr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Queens Court',
                    'Address2' => '24 Queen Street',
                    'Address3' => 'Manchester',
                    'Address4' => '',
                    'CompanyName' => 'SA Medical',
                    'CountryID' => 1,
                    'CreatedDate' => 1569834067,
                    'DoctorID' => 27,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '4180821',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '0',
                    'ModifiedDate' => 1569834067,
                    'Name' => 'Imran ',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'M2 5HX',
                    'Status' => 2,
                    'Surname' => 'Majid',
                    'Telephone' => '0',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '28b Green Lane',
                    'Address2' => 'Dewsbury',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => 'SA Medical',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789446,
                    'DoctorID' => 28,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '6158621',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07525029874',
                    'ModifiedDate' => 1569789446,
                    'Name' => 'Habib',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'WF13 4DH',
                    'Status' => 2,
                    'Surname' => 'Afzal',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '65 OAKWOOD DRIVE',
                    'Address2' => 'HEATON',
                    'Address3' => 'BOLTON',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1570035831,
                    'DoctorID' => 29,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '4741365',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07415700145',
                    'ModifiedDate' => 1570035831,
                    'Name' => 'Imran',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL1 5EH',
                    'Status' => 2,
                    'Surname' => 'Malik',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '7 Wendover Drive',
                    'Address2' => 'Bolton',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => 'SA Medical',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789472,
                    'DoctorID' => 30,
                    'DoctorType' => 1,
                    'Email' => 'suhelahmed@doctors.org.uk',
                    'GMCNO' => '6053020',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07825448004',
                    'ModifiedDate' => 1569789472,
                    'Name' => 'Suhel',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL3 4RX',
                    'Status' => 2,
                    'Surname' => 'Ahmed',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '11 Norfolk Avenue',
                    'Address2' => 'Blackpool',
                    'Address3' => 'Lancs',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569834082,
                    'DoctorID' => 31,
                    'DoctorType' => 3,
                    'Email' => 'davidkelly_1974@hotmail.com',
                    'GMCNO' => '2059452',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '07800 594415',
                    'ModifiedDate' => 1569834082,
                    'Name' => 'David',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'FY2 9QA',
                    'Status' => 2,
                    'Surname' => 'Kelly',
                    'Telephone' => '',
                    'Title' => 'Mr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '5 St Helier Street',
                    'Address2' => 'Bolton',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => 'SIA Medical',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789560,
                    'DoctorID' => 32,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '6117240',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789560,
                    'Name' => 'Azeem',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL3 6TU',
                    'Status' => 2,
                    'Surname' => 'Wahla',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '575/577 Halliwell Road',
                    'Address2' => '',
                    'Address3' => '',
                    'Address4' => 'Bolton',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789625,
                    'DoctorID' => 35,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '2856234',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789625,
                    'Name' => 'Surinder',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL1 8BZ',
                    'Status' => 2,
                    'Surname' => 'Singh',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '',
                    'Address2' => '',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569833957,
                    'DoctorID' => 36,
                    'DoctorType' => 4,
                    'Email' => '',
                    'GMCNO' => '4523452345',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569833957,
                    'Name' => 'Marius',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => '',
                    'Status' => 2,
                    'Surname' => 'Bufty',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '8 Sandfield Walk',
                    'Address2' => 'Liverpool',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => 'SIA MEDICAL',
                    'CountryID' => 1,
                    'CreatedDate' => 1569833964,
                    'DoctorID' => 40,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '6053102',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569833964,
                    'Name' => 'Wayne',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'L13 0AP',
                    'Status' => 2,
                    'Surname' => 'Osborne',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str MUSICESCU GAVRIL Nr 81A',
                    'Address2' => 'Timisoara',
                    'Address3' => '',
                    'Address4' => 'Timis',
                    'CompanyName' => '',
                    'CountryID' => 177,
                    'CreatedDate' => 1569834186,
                    'DoctorID' => 41,
                    'DoctorType' => 2,
                    'Email' => '',
                    'GMCNO' => '814',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569834186,
                    'Name' => 'Claudiu',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => '300425',
                    'Status' => 2,
                    'Surname' => 'Avram',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => NULL,
                    'CountryID' => 1,
                    'CreatedDate' => 1588590169,
                    'DoctorID' => 42,
                    'DoctorType' => 0,
                    'Email' => NULL,
                    'GMCNO' => '9010946',
                    'MedicalInsuranceNo' => NULL,
                    'Mobile' => NULL,
                    'ModifiedDate' => 1588590169,
                    'Name' => 'HR Healthcare',
                    'Notes' => NULL,
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL2 2HH',
                    'Status' => 1,
                    'Surname' => 'Pharmacy',
                    'Telephone' => NULL,
                    'Title' => NULL,
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str Bld Eroilor de la Tisa nr.43-45 bl.E1/A ap.9',
                    'Address2' => '',
                    'Address3' => 'Timisoara',
                    'Address4' => 'Timis',
                    'CompanyName' => '',
                    'CountryID' => 177,
                    'CreatedDate' => 1569833980,
                    'DoctorID' => 43,
                    'DoctorType' => 2,
                    'Email' => '',
                    'GMCNO' => '3109',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569833980,
                    'Name' => 'El Susi',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => '300551',
                    'Status' => 2,
                    'Surname' => 'Suzane',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str Matei Basarab nr 18, bl 62, ap 8',
                    'Address2' => '',
                    'Address3' => 'Timisoara',
                    'Address4' => 'Timis',
                    'CompanyName' => '',
                    'CountryID' => 177,
                    'CreatedDate' => 1569833992,
                    'DoctorID' => 44,
                    'DoctorType' => 2,
                    'Email' => 'paul.ctanase@yahoo.com',
                    'GMCNO' => '4354',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569833992,
                    'Name' => 'Paul Christian',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'apple786',
                    'Postcode' => '300359',
                    'Status' => 2,
                    'Surname' => 'Tanase',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => 'test',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => NULL,
                    'CountryID' => 1,
                    'CreatedDate' => 1611158704,
                    'DoctorID' => 53,
                    'DoctorType' => 1,
                    'Email' => 'adele.farrell@hrhealthcare.group',
                    'GMCNO' => '4625128',
                    'MedicalInsuranceNo' => NULL,
                    'Mobile' => NULL,
                    'ModifiedDate' => 1611158704,
                    'Name' => 'Adele',
                    'Notes' => 'https://www.gmc-uk.org/doctors/4625128',
                    'ParentID' => NULL,
                    'Password' => 'apple786',
                    'Postcode' => 'BL2 2HH',
                    'Status' => 0,
                    'Surname' => 'Farrell',
                    'Telephone' => NULL,
                    'Title' => 'Dr',
                    'Username' => 'adele.farrell',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '21 Dover Drive',
                    'Address2' => 'Regent Meadows',
                    'Address3' => 'Telford',
                    'Address4' => 'Shropshire',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789586,
                    'DoctorID' => 46,
                    'DoctorType' => 1,
                    'Email' => 'nitinshori@aol.com',
                    'GMCNO' => '6047293',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789586,
                    'Name' => 'Nitin',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'TF1 5TD',
                    'Status' => 2,
                    'Surname' => 'Shori',
                    'Telephone' => '+447590 260079',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str Victor Valcovici nr 8',
                    'Address2' => 'Timisoara',
                    'Address3' => '',
                    'Address4' => 'Timis',
                    'CompanyName' => '',
                    'CountryID' => 177,
                    'CreatedDate' => 1569834054,
                    'DoctorID' => 47,
                    'DoctorType' => 2,
                    'Email' => 'avram_rlc@yahoo.com',
                    'GMCNO' => '3824',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569834054,
                    'Name' => 'Raluca',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => '',
                    'Postcode' => '300503',
                    'Status' => 2,
                    'Surname' => 'Avram',
                    'Telephone' => '0257457474',
                    'Title' => 'Dr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str Matei Basarab nr 18, bl 62, ap 8',
                    'Address2' => '',
                    'Address3' => 'Timisoara',
                    'Address4' => 'Timis',
                    'CompanyName' => '',
                    'CountryID' => 177,
                    'CreatedDate' => 1586354641,
                    'DoctorID' => 48,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '7514443',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1586354641,
                    'Name' => 'Elena',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'apple786',
                    'Postcode' => '300359',
                    'Status' => 2,
                    'Surname' => 'Tanase',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Str. Ion Popovici Banateanu nr 29',
                    'Address2' => '',
                    'Address3' => '',
                    'Address4' => 'Timisoara',
                    'CompanyName' => '',
                    'CountryID' => 177,
                    'CreatedDate' => 1586354562,
                    'DoctorID' => 49,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '6162948',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1586354562,
                    'Name' => 'Khalid',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => 'apple786',
                    'Postcode' => '300370',
                    'Status' => 2,
                    'Surname' => 'Efleih Hassan',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Test Address',
                    'Address2' => '',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1536402769,
                    'DoctorID' => 50,
                    'DoctorType' => 4,
                    'Email' => '',
                    'GMCNO' => '123456',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1536402769,
                    'Name' => 'Test',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => '',
                    'Postcode' => '',
                    'Status' => 1,
                    'Surname' => 'Doctor',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting, Britannia Way, Bolton',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => 'NULL',
                    'CountryID' => 1,
                    'CreatedDate' => 1626903237,
                    'DoctorID' => 51,
                    'DoctorType' => 5,
                    'Email' => 'NULL',
                    'GMCNO' => '430652',
                    'MedicalInsuranceNo' => 'NULL',
                    'Mobile' => 'NULL',
                    'ModifiedDate' => 1626903237,
                    'Name' => 'Daniel',
                    'Notes' => 'https://www.medicalcouncil.ie/public-information/check-the-register/search-results/?regno=430652&doctorid=50037424',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL2 2HH',
                    'Status' => 1,
                    'Surname' => 'Atkinson',
                    'Telephone' => 'NULL',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => '65 Woodcock Close',
                    'Address2' => 'Rubery',
                    'Address3' => 'Birmingham',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1569789313,
                    'DoctorID' => 52,
                    'DoctorType' => 1,
                    'Email' => '',
                    'GMCNO' => '7094204',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1569789313,
                    'Name' => 'Alina Nicoleta',
                    'Notes' => '',
                    'ParentID' => NULL,
                    'Password' => '',
                    'Postcode' => 'B31 5EH',
                    'Status' => 2,
                    'Surname' => 'Cobzariu',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Rooskey Street',
                    'Address2' => 'Roscommon',
                    'Address3' => '',
                    'Address4' => '',
                    'CompanyName' => '',
                    'CountryID' => 105,
                    'CreatedDate' => 1611158337,
                    'DoctorID' => 54,
                    'DoctorType' => 5,
                    'Email' => '',
                    'GMCNO' => '424855',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1611158337,
                    'Name' => 'Lacramioara',
                    'Notes' => 'https://www.medicalcouncil.ie/public-information/check-the-register/search-results/?regno=424855&doctorid=50021974',
                    'ParentID' => NULL,
                    'Password' => '',
                    'Postcode' => 'N41P9KO',
                    'Status' => 2,
                    'Surname' => 'Burlacu',
                    'Telephone' => '',
                    'Title' => 'Dr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => '',
                    'CountryID' => 1,
                    'CreatedDate' => 1611158571,
                    'DoctorID' => 55,
                    'DoctorType' => 3,
                    'Email' => '',
                    'GMCNO' => '2070724',
                    'MedicalInsuranceNo' => '',
                    'Mobile' => '',
                    'ModifiedDate' => 1611158571,
                    'Name' => 'Craig',
                    'Notes' => 'https://www.pharmacyregulation.org/registers/pharmacist/registrationnumber/2070724',
                    'ParentID' => NULL,
                    'Password' => '',
                    'Postcode' => 'BL2 2HH',
                    'Status' => 1,
                    'Surname' => 'Marsh',
                    'Telephone' => '',
                    'Title' => 'Mr',
                    'Username' => '',
                ),

                array(
                    'AccessedDate' => 0,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => NULL,
                    'CountryID' => 1,
                    'CreatedDate' => 1611158601,
                    'DoctorID' => 56,
                    'DoctorType' => 3,
                    'Email' => NULL,
                    'GMCNO' => '2084212',
                    'MedicalInsuranceNo' => NULL,
                    'Mobile' => NULL,
                    'ModifiedDate' => 1611158601,
                    'Name' => 'Raisa',
                    'Notes' => 'https://www.pharmacyregulation.org/registers/pharmacist/registrationnumber/2084212',
                    'ParentID' => NULL,
                    'Password' => NULL,
                    'Postcode' => 'BL2 2HH',
                    'Status' => 0,
                    'Surname' => 'Mohammed',
                    'Telephone' => NULL,
                    'Title' => 'Miss',
                    'Username' => NULL,
                ),

                array(
                    'AccessedDate' => NULL,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => 'Docdales',
                    'CountryID' => 1,
                    'CreatedDate' => 1624460997,
                    'DoctorID' => 69,
                    'DoctorType' => 1,
                    'Email' => 'daniel.atkinson@hrhealthcare.group',
                    'GMCNO' => '4624794',
                    'MedicalInsuranceNo' => 'xxxx',
                    'Mobile' => '01204 559999',
                    'ModifiedDate' => 1624460997,
                    'Name' => 'Daniel',
                    'Notes' => 'https://www.gmc-uk.org/doctors/4624794',
                    'ParentID' => NULL,
                    'Password' => 'NULL',
                    'Postcode' => 'BL2 2HH',
                    'Status' => 1,
                    'Surname' => 'Atkinson',
                    'Telephone' => '01204 559999',
                    'Title' => 'Dr',
                    'Username' => 'NULL',
                ),

                array(
                    'AccessedDate' => NULL,
                    'Address1' => 'Unit 18',
                    'Address2' => 'Waters Meeting',
                    'Address3' => 'Britannia Way',
                    'Address4' => 'Bolton',
                    'CompanyName' => NULL,
                    'CountryID' => 1,
                    'CreatedDate' => NULL,
                    'DoctorID' => 70,
                    'DoctorType' => 3,
                    'Email' => NULL,
                    'GMCNO' => '2070338',
                    'MedicalInsuranceNo' => NULL,
                    'Mobile' => NULL,
                    'ModifiedDate' => NULL,
                    'Name' => 'Ruaraidh',
                    'Notes' => 'https://www.pharmacyregulation.org/registers/pharmacist/registrationnumber/2070338',
                    'ParentID' => NULL,
                    'Password' => NULL,
                    'Postcode' => 'BL2 2HH',
                    'Status' => 1,
                    'Surname' => 'Buckenham',
                    'Telephone' => NULL,
                    'Title' => 'Mr',
                    'Username' => NULL,
                ),
            )
        );


    }
}